language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      python: 2.7
      sudo: required
      language: generic
    - os: linux
      python: 3.3
    - os: osx
      python: 3.3
      sudo: required
      language: generic
    - os: linux
      python: 3.4
    - os: osx
      python: 3.4
      sudo: required
      language: generic
    - os: linux
      python: 3.5
    - os: osx
      python: 3.5
      sudo: required
      language: generic
    - os: linux
      python: 3.6
    - os: osx
      python: 3.6
      sudo: required
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "2.7"  ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" != "2.7" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" != "2.7"  ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install: "python setup.py install"
script: "python setup.py test"

notifications:
  email:
    recipients:
      - alerts+ci@opengov.com
    on_success: change
    on_failure: always
