language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      language: python
      python: 3.7
      dist: xenial
      sudo: true
    - os: linux
      language: python
      python: 3.6
      # Don't allow the python library to download (check if it can use an installed hunspell)
      env: SKIP_DOWNLOAD=true
      dist: artful
      sudo: true

before_install:
  # For debug purposes
  - if [[ "$SKIP_DOWNLOAD" == "true" ]]; then sudo apt-cache search hunspell; fi
  - if [[ "$SKIP_DOWNLOAD" == "true" ]]; then sudo apt-get install libhunspell-1.3-0 libhunspell-dev; fi
  # For debug purposes
  - python --version
install: "python setup.py install && pip install -r requirements-test.txt"
script: "pytest"

notifications:
  email:
    recipients:
      - mseal007@gmail.com
    on_success: change
    on_failure: always
