language: python
matrix:
  include:
  - os: linux
    python: 3.5
    env:
    - CIBW_BUILD: cp35-*
  - os: linux
    python: 3.6
    env:
    - CIBW_BUILD: cp36-*
  - os: linux
    python: 3.7
    env:
    - CIBW_BUILD: cp37-*
  - os: linux
    python: 3.8
    env:
    - CIBW_BUILD: cp38-*
  - os: osx
    language: shell
    env:
    - PYENV_VERSION: 3.5-dev
    - CIBW_BUILD: cp35-*
    - HOMEBREW_NO_INSTALL_CLEANUP: 1
    - HOMEBREW_NO_AUTO_UPDATE: 1
  - os: osx
    language: shell
    env:
    - PYENV_VERSION: 3.6-dev
    - CIBW_BUILD: cp36-*
    - HOMEBREW_NO_INSTALL_CLEANUP: 1
    - HOMEBREW_NO_AUTO_UPDATE: 1
  - os: osx
    language: shell
    env:
    - PYENV_VERSION: 3.7-dev
    - CIBW_BUILD: cp37-*
    - HOMEBREW_NO_INSTALL_CLEANUP: 1
    - HOMEBREW_NO_AUTO_UPDATE: 1
  - os: osx
    language: shell
    env:
    - PYENV_VERSION: 3.8-dev
    - CIBW_BUILD: cp38-*
    - HOMEBREW_NO_INSTALL_CLEANUP: 1
    - HOMEBREW_NO_AUTO_UPDATE: 1
  - os: windows
    language: shell
    env:
    - PYENV_VERSION: 3.6.8
    - PYENV_PATH: "/c/Python36"
    - CIBW_BUILD: cp36-*
    - MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin
  - os: windows
    language: shell
    env:
    - PYENV_VERSION: 3.7.8
    - PYENV_PATH: "/c/Python37"
    - CIBW_BUILD: cp37-*
    - MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin
  - os: windows
    language: shell
    env:
    - PYENV_VERSION: 3.8.5
    - PYENV_PATH: "/c/Python38"
    - CIBW_BUILD: cp38-*
    - MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin
before_install:
- |-
  case $TRAVIS_OS_NAME in
    linux)
      sudo apt install -y autoconf automake autopoint libtool
      pip install -U pip
      python --version
      ;;
    osx)
      brew install autoconf automake libtool gettext
      brew link gettext --force
      eval "$(pyenv init -)"
      pyenv install $PYENV_VERSION
      pyenv global $PYENV_VERSION
      pyenv rehash
      pip install -U pip
      python --version
      ;;
    windows)
      choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      choco install python --version $PYENV_VERSION
      export PATH="$PYENV_PATH:$PYENV_PATH/Scripts:$MSBUILD_PATH:$PATH"
      python -m ensurepip
      pip install -U pip
      python --version
      ;;
  esac
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install -r requirements-test.txt
- pip install cibuildwheel
- touch .cibuildwheel
- python setup.py build
- CYHUNSPELL_FORCE_BUILD=0 pip install .
- rm -rf build
- rm -rf external/build
script:
- python -m pytest -vv
- rm hunspell/*.so || true
- rm hunspell/*.dylib || true
- rm hunspell/*.pyd || true
- python -m cibuildwheel --output-dir wheelhouse
- ls wheelhouse
- if [ "${TRAVIS_TAG:-}" != "" ]; then python -m twine upload --skip-existing wheelhouse/*;
  fi
notifications:
  email:
    recipients:
    - mseal007@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: CAg9KSq5QBVpSqllD+E+aA/4eeD9oq5r3bsC72RjaeeUHdhVJCRGva0ijycDLsA8P9y72jyndMGfl2/vfutX4JPdA9FWAMwaKAL4VgKuoZlgAxp7Zo8wjeERRll4Tef3VJao/WryAumutQO7/5T+J4xDb6Turz6xAaOdeyVmgUhtg50FSb30POpKCh9LtcOZRnGjrodKB+oQDfGXAdbFdqn5ud7Q2gw9PAhUfd2tyK1dA4zM0DC5eU1d4Fyqk5zATmMDmnvkDYio9RXLN/4FD6sc7ZnknpM7zjBpK2MlmZNQ6tNSFXh4exhHRBIsYpthwwvIit87K9MZB7FZC2eP8UrTsCXOD9Y9JRD7icGYrM0A8WeezFATvbkkVIHmkN1SGQm9uPvIrYMg/ZulMLhx2KBqKwg1nwVXL+QN1O3jJL23WI3aqHDSGv2HaKI18/e2MqLNeM/pdOZMbRYqj3svq2aeDPdbIZKmO583buRsleH7Kw8WCUho/AifyodnywYp3wSHGn/ixb/xE79aSCuuCaPKaWIFf/sJGHSyP1+rZOvgazwolQ35aSSdJsPhg5Rc49Tc5nLMf5UqrnY42EGMdpdxF/EGTVg91eZRuz2+cTeV6Jq8rGKIqMQviLn46FyM2yuRcjdrozu/Gyj1qMfKxoqFode57Yo0HFDLO287lQc=
env:
  global:
  - CYHUNSPELL_FORCE_BUILD: 1
  - CIBW_ENVIRONMENT: CYHUNSPELL_FORCE_BUILD=1
