language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      python: 2.7
      sudo: required
    - os: linux
      python: 3.3
    - os: osx
      python: 3.3
      sudo: required
    - os: linux
      python: 3.4
    - os: osx
      python: 3.4
      sudo: required
    - os: linux
      python: 3.5
    - os: osx
      python: 3.5
      sudo: required
    - os: linux
      python: 3.6
    - os: osx
      python: 3.6
      sudo: required

install: "python setup.py install"
script: "python setup.py test"

notifications:
  email:
    recipients:
      - alerts+ci@opengov.com
    on_success: change
    on_failure: always
