# Taken from https://github.com/pygame/pygame/blob/master/appveyor.yml

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    # TODO: Fix?
    # Python 2 install tooling is problematic for the windows setup being tested
    # - PYTHON: "C:\\Python27"
    #   PYTHON_VERSION: "2.7.13"
    #   PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "32"

    # Not available yet
    # - PYTHON: "C:\\Python37"
    #   PYTHON_VERSION: "3.7.0"
    #   PYTHON_ARCH: "32"

    # TODO: Fix?
    # Python 2 install tooling is problematic for the windows setup being tested
    # - PYTHON: "C:\\Python27-x64"
    #   PYTHON_VERSION: "2.7.13"
    #   PY2: "true"
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"

    # Not available yet
    # - PYTHON: "C:\\Python37-x64"
    #   PYTHON_VERSION: "3.7.0"
    #   PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%/python -m pip install -U pip"  # Upgrade pip
  # Install the depdencies (hunspell builds happen here)
  - "%PYTHON%/python setup.py install"

# Appveyor's build step is specific to .NET projects, so we build in the
# install step instead.
build: off

test_script:
  - "%PYTHON%/python setup.py test"
